# Generated by Django 5.2.4 on 2025-08-09 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IGDMThread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_thread_id",
                    models.CharField(max_length=100, verbose_name="スレッドID"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
            ],
            options={
                "verbose_name": "InstagramDMスレッド",
                "verbose_name_plural": "InstagramDMスレッド",
                "db_table": "meta_ig_dm_threads",
            },
        ),
        migrations.CreateModel(
            name="InstagramBusinessAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=255, verbose_name="表示名"),
                ),
                (
                    "username",
                    models.CharField(max_length=255, verbose_name="ユーザー名"),
                ),
                (
                    "external_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="外部ID"
                    ),
                ),
                (
                    "token_expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="トークン期限"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "ig_business_id",
                    models.CharField(max_length=100, verbose_name="IGビジネスID"),
                ),
                (
                    "fb_page_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="FacebookページID",
                    ),
                ),
                (
                    "access_token",
                    models.TextField(
                        blank=True, null=True, verbose_name="アクセストークン"
                    ),
                ),
                (
                    "webhook_verify_token",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Webhook検証トークン",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instagramビジネスアカウント",
                "verbose_name_plural": "Instagramビジネスアカウント",
                "db_table": "meta_ig_accounts",
            },
        ),
        migrations.CreateModel(
            name="IGDMMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("IN", "受信"), ("OUT", "送信")],
                        max_length=3,
                        verbose_name="方向",
                    ),
                ),
                ("text", models.TextField(verbose_name="本文")),
                ("sent_at", models.DateTimeField(verbose_name="送信時間")),
                (
                    "raw_json",
                    models.JSONField(blank=True, default=dict, verbose_name="RAW"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="ig.igdmthread",
                    ),
                ),
            ],
            options={
                "verbose_name": "InstagramDMメッセージ",
                "verbose_name_plural": "InstagramDMメッセージ",
                "db_table": "meta_ig_dm_messages",
            },
        ),
        migrations.CreateModel(
            name="IGWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(max_length=100, verbose_name="イベント種別"),
                ),
                (
                    "received_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="受信日時"),
                ),
                ("payload", models.JSONField(default=dict, verbose_name="ペイロード")),
                (
                    "processed",
                    models.BooleanField(default=False, verbose_name="処理済"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhook_events",
                        to="ig.instagrambusinessaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "InstagramWebhookイベント",
                "verbose_name_plural": "InstagramWebhookイベント",
                "db_table": "meta_ig_webhook_events",
            },
        ),
        migrations.CreateModel(
            name="IGScheduledPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="タイトル")),
                ("topic", models.CharField(max_length=255, verbose_name="トピック")),
                ("body", models.TextField(verbose_name="本文")),
                (
                    "media_url",
                    models.URLField(blank=True, null=True, verbose_name="メディアURL"),
                ),
                ("scheduled_at", models.DateTimeField(verbose_name="予約日時")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "下書き"),
                            ("APPROVED", "承認済み"),
                            ("SENT", "送信済み"),
                            ("FAILED", "失敗"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_posts",
                        to="ig.instagrambusinessaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instagram予約投稿",
                "verbose_name_plural": "Instagram予約投稿",
                "db_table": "meta_ig_scheduled_posts",
            },
        ),
        migrations.CreateModel(
            name="IGPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_post_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="外部投稿ID"
                    ),
                ),
                ("posted_at", models.DateTimeField(verbose_name="投稿時間")),
                (
                    "caption",
                    models.TextField(blank=True, null=True, verbose_name="本文"),
                ),
                (
                    "media_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="メディアタイプ"
                    ),
                ),
                (
                    "media_url",
                    models.URLField(blank=True, null=True, verbose_name="メディアURL"),
                ),
                ("like_count", models.IntegerField(default=0, verbose_name="いいね数")),
                (
                    "view_count",
                    models.IntegerField(blank=True, null=True, verbose_name="閲覧数"),
                ),
                (
                    "impressions",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="インプレッション"
                    ),
                ),
                ("raw_json", models.JSONField(default=dict, verbose_name="取得JSON")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="ig.instagrambusinessaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instagram投稿",
                "verbose_name_plural": "Instagram投稿",
                "db_table": "meta_ig_posts",
            },
        ),
        migrations.AddField(
            model_name="igdmthread",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dm_threads",
                to="ig.instagrambusinessaccount",
            ),
        ),
        migrations.CreateModel(
            name="IGBroadcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="名称")),
                (
                    "segment",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="セグメント"
                    ),
                ),
                ("body", models.TextField(verbose_name="本文")),
                ("send_at", models.DateTimeField(verbose_name="送信日時")),
                (
                    "status",
                    models.CharField(
                        default="DRAFT", max_length=20, verbose_name="ステータス"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broadcasts",
                        to="ig.instagrambusinessaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instagram時間指定配信",
                "verbose_name_plural": "Instagram時間指定配信",
                "db_table": "meta_ig_broadcasts",
            },
        ),
        migrations.CreateModel(
            name="IGAutoReplyTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="名称")),
                ("body", models.TextField(verbose_name="本文")),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_reply_templates",
                        to="ig.instagrambusinessaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instagram自動返信テンプレート",
                "verbose_name_plural": "Instagram自動返信テンプレート",
                "db_table": "meta_ig_auto_reply_templates",
            },
        ),
        migrations.CreateModel(
            name="IGAutoReplyRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="名称")),
                ("keywords", models.TextField(verbose_name="キーワード")),
                (
                    "delay_minutes",
                    models.IntegerField(default=0, verbose_name="遅延分"),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="ig.igautoreplytemplate",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_reply_rules",
                        to="ig.instagrambusinessaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instagram自動返信ルール",
                "verbose_name_plural": "Instagram自動返信ルール",
                "db_table": "meta_ig_auto_reply_rules",
            },
        ),
    ]
