# Generated by Django 5.2.4 on 2025-09-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ig', '0003_alter_instagrambusinessaccount_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrambusinessaccount',
            name='access_token',
            field=models.TextField(blank=True, null=True, verbose_name='アクセストークン'),
        ),
        migrations.AlterField(
            model_name='instagrambusinessaccount',
            name='fb_page_id',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='FacebookページID'),
        ),
        migrations.AlterField(
            model_name='instagrambusinessaccount',
            name='ig_business_id',
            field=models.CharField(db_index=True, max_length=32, unique=True, verbose_name='IGビジネスID'),
        ),
        migrations.AlterField(
            model_name='instagrambusinessaccount',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='トークン期限'),
        ),
        migrations.AlterField(
            model_name='instagrambusinessaccount',
            name='webhook_verify_token',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Webhook検証トークン'),
        ),
        migrations.AddIndex(
            model_name='instagrambusinessaccount',
            index=models.Index(fields=['ig_business_id'], name='meta_ig_acc_ig_busi_f81f04_idx'),
        ),
        migrations.AddIndex(
            model_name='instagrambusinessaccount',
            index=models.Index(fields=['fb_page_id'], name='meta_ig_acc_fb_page_007dfc_idx'),
        ),
    ]
