# Generated by Django 5.2.4 on 2025-09-29 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ig', '0004_alter_instagrambusinessaccount_access_token_and_more'),
        ('social', '0003_dmcontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='IGDMReplyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_id', models.CharField(max_length=64)),
                ('biz_ig_id', models.CharField(blank=True, default='', max_length=64)),
                ('text', models.TextField()),
                ('ok', models.BooleanField(default=False)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ig_reply_logs', to='social.dmmessage')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['dm', '-created_at'], name='ig_igdmrepl_dm_id_933c58_idx')],
            },
        ),
    ]
