# Generated by Django 5.2.4 on 2025-09-29 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ig', '0005_igdmreplylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrambusinessaccount',
            name='long_lived_user_token',
            field=models.TextField(blank=True, help_text='Graph API Explorerで生成→60日に延長したユーザートークン。自動更新の起点になります。', null=True, verbose_name='長期ユーザートークン（User）'),
        ),
        migrations.AddField(
            model_name='instagrambusinessaccount',
            name='page_access_token',
            field=models.TextField(blank=True, help_text='ensure_fresh_page_token により上書きされます。空でも可。', null=True, verbose_name='ページアクセストークン（自動更新で上書き）'),
        ),
        migrations.AlterField(
            model_name='instagrambusinessaccount',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, help_text='表示用。自動更新の必須ではありません。', null=True, verbose_name='ページトークン期限'),
        ),
    ]
