# Generated by Django 5.2.4 on 2026-02-26 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ig', '0008_alter_igpost_media_url_alter_igscheduledpost_media_url'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='igpostinsight',
            new_name='meta_ig_pos_post_id_342b0f_idx',
            old_name='meta_ig_pos_post_id_idx',
        ),
    ]
