"""
Django settings for app project.
Generated by 'django-admin startproject' using Django 5.2.4.
"""

from pathlib import Path
import os
from urllib.parse import urlparse, parse_qs

# === Paths ===
BASE_DIR = Path(__file__).resolve().parent.parent

# === Core toggles from .env ===
DEBUG = os.getenv("DJANGO_DEBUG", "False").lower() == "true"
hosts_raw = os.getenv("DJANGO_ALLOWED_HOSTS", "")

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

# 2) CSRF 設定：.env の値を使う。無ければ https をデフォルト
_csrf_raw = os.getenv(
    "DJANGO_CSRF_TRUSTED_ORIGINS",
    "https://muitobem.top,https://www.muitobem.top",
)
CSRF_TRUSTED_ORIGINS = [h.strip() for h in _csrf_raw.split(",") if h.strip()]

# 3) Cookie を HTTPS 専用に
SESSION_COOKIE_SECURE = os.getenv("DJANGO_SESSION_COOKIE_SECURE", "True").lower() == "true"
CSRF_COOKIE_SECURE    = os.getenv("DJANGO_CSRF_COOKIE_SECURE", "True").lower() == "true"
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_DOMAIN = ".muitobem.top"
CSRF_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7         # 24時間 * 7（任意）
SESSION_SAVE_EVERY_REQUEST = True          # ←これがスライド延長
SESSION_EXPIRE_AT_BROWSER_CLOSE = False 
#CSRF_TRUSTED_ORIGINS = ["https://muitobem.top"]

# 4) HTTPS リダイレクト（Caddy で 80→443 は済みだがアプリ側も一応）
SECURE_SSL_REDIRECT = os.getenv("DJANGO_SECURE_SSL_REDIRECT", "True").lower() == "true"

#ALLOWED_HOSTS = [h for h in os.getenv("DJANGO_ALLOWED_HOSTS", "").split(",") if h] or []
ALLOWED_HOSTS = [h.strip() for h in hosts_raw.split(",") if h.strip()]
try:
    if "testserver" not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append("testserver")
except NameError:
    ALLOWED_HOSTS = ["testserver"]
    
LANGUAGE_CODE = "ja"
TIME_ZONE = os.getenv("DJANGO_TIME_ZONE", "Asia/Tokyo")
USE_I18N = True
USE_TZ = True  # 必要に応じて False へ（JST naive 運用にしたい場合）

# === Secret Key ===
# 既存のリテラルを既定値にしつつ、.env の DJANGO_SECRET_KEY があれば優先
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-aj98%v(fzaudoz%975*eg$$f29m=!lmwra082lg&5v_t3!^$bw"
)

# === Applications ===
INSTALLED_APPS = [
    # Ensure AdminLTE templates override default admin templates
    #"django_adminlte3",
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "sns_core",
    "social",
    "webhooks",
    "social_core",
    "ig",
    "th",
    "social_webhooks",
    "social_scheduler",
    "yaget.apps.YagetConfig",
    "app.console.apps.ConsoleConfig",
]

# === Middleware ===
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# === URLs / WSGI ===
ROOT_URLCONF = "app.urls"
WSGI_APPLICATION = "app.wsgi.application"

# === Templates ===
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                            ],
        },
    },
]

JAZZMIN_SETTINGS = {
    # 画面タイトルなど
    "site_title": "SNS運用 管理画面",
    "site_header": "SNS運用 管理画面",
    "site_brand": "SNS運用",
    "welcome_sign": "SNS運用管理",
    "show_ui_builder": False,     # 右下のテーマ切替を消す
    "navigation_expanded": False, # 左メニューはデフォ閉じ

    # アイコン（存在している管理モデルに合わせて）
    "icons": {
        # auth
        "auth.User": "fa fa-user",
        "auth.Group": "fa fa-users",

        # ig
        "ig.InstagramBusinessAccount": "fab fa-instagram",
        "ig.IGPost": "fa fa-image",
        "ig.IGScheduledPost": "fa fa-calendar-check",
        "ig.IGWebhookEvent": "fa fa-bell",

        # social（共通SNS）
        "social.AutoReplyRule": "fa fa-reply-all",
        "social.DMMessage": "fa fa-envelope",
        "social.DMReplyTemplate": "fa fa-file-alt",
        "social.FacebookAccount": "fab fa-facebook",
        "social.InstagramAccount": "fab fa-instagram",
        "social.Job": "fa fa-tasks",
        "social.Post": "fa fa-list",
        "social.ScheduledPost": "fa fa-clock",
        "social.ThreadsAccount": "fa fa-comments",
        "social.ThreadsApp": "fa fa-cog",
        "social.WebhookEvent": "fa fa-bolt",

        # th（Threads）
        "th.ThreadsAccount": "fa fa-comments",
        "th.THPost": "fa fa-comment",
        "th.THScheduledPost": "fa fa-calendar-alt",
        "th.THWebhookEvent": "fa fa-bell",
        "th.THBuzzAuthor": "fa fa-user-circle",
        "th.THBuzzPost": "fa fa-fire",
        "th.THBuzzSearchJob": "fa fa-search",
    },

    # 左ナビでのアプリ表示順
    "order_with_respect_to": [
        "ig",
        "social",
        "th",
        "auth",
    ],

    # 左ナビに置く「便利リンク」（※存在確認済みURLだけ入れています）
    "custom_links": {
        # 共通SNS：管理外のビューだけ
        # "social": [
        #     {"name": "投稿インポート", "url": "social:post-import", "icon": "fa fa-file-import"},
        #     {"name": "投稿同期",       "url": "social:post-sync",   "icon": "fa fa-sync"},
        # ],
        # "ig": [] を消す（または ig キー自体を削除）
        # "th": [] を消す（または th キー自体を削除）

        # 認証はモデルが出るので custom_links は不要
        # "auth": [] も削除
    },
    "topmenu_links": [
        {"name": "ダッシュボード",        "url": "console:index",            "permissions": ["auth.view_user"]},
        {"name": "アカウント連携",        "url": "console:accounts",         "permissions": ["auth.view_user"]},
        {"name": "権限チェック",          "url": "console:permissions",      "permissions": ["auth.view_user"]},
        {"name": "投稿インポート",        "url": "social:post-import",       "permissions": ["auth.view_user"]},
        {"name": "投稿同期",              "url": "social:post-sync",         "permissions": ["auth.view_user"]},
        {"name": "Webhook 受信テスト",    "url": "console:webhook_test",     "permissions": ["auth.view_user"]},
        {"name": "Webhook イベント一覧",  "url": "console:webhook_events",   "permissions": ["auth.view_user"]},
        # ※ /console/webhook/setup/ は現在 views.webhook_test に紐付いています（routes参照）
        {"name": "Webhook 設定",          "url": "console:webhook_setup",    "permissions": ["auth.view_user"]},

        # セットアップ・テンプレート
        {"name": "セットアップ",          "url": "console:setup_env",        "permissions": ["auth.view_user"]},
        {"name": "テンプレ一覧",          "url": "console:tpl_list",         "permissions": ["auth.view_user"]},
        {"name": "テンプレ新規",          "url": "console:tpl_new",          "permissions": ["auth.view_user"]},
        {"name": "テンプレ書出し",        "url": "console:tpl_export",       "permissions": ["auth.view_user"]},
        {"name": "テンプレ読込",          "url": "console:tpl_import",       "permissions": ["auth.view_user"]},

        # バズ投稿取得
        {"name": "バズ投稿取得",          "url": "console:buzz_search",      "permissions": ["auth.view_user"]},
        {"name": "急成長ランキング",      "url": "console:buzz_growth_ranking", "permissions": ["auth.view_user"]},
        {"name": "一括巡回",              "url": "console:buzz_keyword_scan",   "permissions": ["auth.view_user"]},
        {"name": "トレンド分析",          "url": "console:buzz_trends",         "permissions": ["auth.view_user"]},

        # 集客自動化 (Phase C)
        {"name": "投稿文AI生成",          "url": "console:content_generator",    "permissions": ["auth.view_user"]},
        {"name": "予約投稿管理",          "url": "console:scheduled_posts",      "permissions": ["auth.view_user"]},
        {"name": "IG投稿管理",            "url": "console:ig_post_manager",      "permissions": ["auth.view_user"]},
        {"name": "パフォーマンス分析",    "url": "console:post_analytics",       "permissions": ["auth.view_user"]},
        {"name": "タロットリール生成",    "url": "console:tarot_reel_gen",       "permissions": ["auth.view_user"]},

        # DM・鑑定 (Phase D)
        {"name": "DM受信管理",            "url": "console:dm_inbox",             "permissions": ["auth.view_user"]},
        {"name": "AI鑑定文生成",          "url": "console:appraisal_gen",        "permissions": ["auth.view_user"]},
        {"name": "自動返信設定",          "url": "console:auto_reply_settings",  "permissions": ["auth.view_user"]},

        # ヘルプ/ログ
        {"name": "統合ガイド",            "url": "console:help",             "permissions": ["auth.view_user"]},
        {"name": "ログ",                  "url": "console:logs",             "permissions": ["auth.view_user"]},
        {"name": "接続テスト",            "url": "console:connection_test",  "permissions": ["auth.view_user"]},
        {"name": "接続テスト",            "url": "console:connection_test",  "permissions": ["auth.view_user"]},
    ],
    "custom_js": "js/mobile_nav_v2.js",
}

# Top menu buttons are intentionally disabled in favor of the structured sidebar accordion.
JAZZMIN_SETTINGS["topmenu_links"] = []

# === Database (env優先 → 個別MYSQL_* → SQLite fallback) ===
def _db_from_url(url: str):
    u = urlparse(url)
    return {
        "ENGINE": "django.db.backends.mysql",
        "NAME": u.path.lstrip("/"),
        "USER": u.username or "",
        "PASSWORD": u.password or "",
        "HOST": u.hostname or "",
        "PORT": u.port or 3306,
        "OPTIONS": {"charset": parse_qs(u.query).get("charset", ["utf8mb4"])[0]},
    }

DATABASE_URL = os.getenv("DATABASE_URL")
if DATABASE_URL:
    DATABASES = {"default": _db_from_url(DATABASE_URL)}
else:
    MYSQL_DB = os.getenv("MYSQL_DATABASE")
    MYSQL_USER = os.getenv("MYSQL_USER")
    MYSQL_PASSWORD = os.getenv("MYSQL_PASSWORD")
    MYSQL_HOST = os.getenv("MYSQL_HOST", "db")
    MYSQL_PORT = int(os.getenv("MYSQL_PORT", "3306"))
    if MYSQL_DB and MYSQL_USER and MYSQL_PASSWORD:
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.mysql",
                "NAME": MYSQL_DB,
                "USER": MYSQL_USER,
                "PASSWORD": MYSQL_PASSWORD,
                "HOST": MYSQL_HOST,
                "PORT": MYSQL_PORT,
                "OPTIONS": {"charset": "utf8mb4"},
            }
        }
    else:
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.sqlite3",
                "NAME": BASE_DIR / "db.sqlite3",
            }
        }

# === Static files ===
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "deploy"        # collectstatic の出力（nginx が /static/ で配信）
# プロジェクト内の追加静的ファイルがあるなら有効化
STATICFILES_DIRS = [BASE_DIR / "static"] if (BASE_DIR / "static").exists() else []

# === Primary key default ===
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# === Instagram / Threads settings (envで上書き可能) ===
INSTAGRAM_PROFESSIONAL_ID = os.getenv("INSTAGRAM_PROFESSIONAL_ID", "17841475861395637")

# Threads API
THREADS_API_BASE_URL = os.getenv("THREADS_API_BASE_URL", "https://graph.threads.net/v1.0")
THREADS_APP_ID = os.getenv("META_THREADS_APP_ID", os.getenv("TH_APP_ID", ""))
THREADS_APP_SECRET = os.getenv("META_THREADS_APP_SECRET", os.getenv("TH_APP_SECRET", ""))
THREADS_USER_ACCESS_TOKEN = os.getenv("META_THREADS_ACCESS_TOKEN", os.getenv("THREADS_ACCESS_TOKEN", ""))
THREADS_WEBHOOK_VERIFY_TOKEN = os.getenv("THREADS_WEBHOOK_VERIFY_TOKEN",
                                         os.getenv("META_THREADS_WEBHOOK_VERIFY_TOKEN", ""))
THREADS_WEBHOOK_SECRET = os.getenv("THREADS_WEBHOOK_SECRET", THREADS_APP_SECRET)

# Facebook/Instagram
FACEBOOK_APP_ID = os.getenv("FACEBOOK_APP_ID", "")
FACEBOOK_APP_SECRET = os.getenv("FACEBOOK_APP_SECRET", "")
IG_APP_ID = os.getenv("META_IG_APP_ID", "")
IG_APP_SECRET = os.getenv("META_IG_APP_SECRET", "")
IG_REDIRECT_URI = os.getenv("META_IG_REDIRECT_URI", "")
VERIFY_TOKEN_IG = os.getenv("VERIFY_TOKEN_IG", "test_token_ig")
VERIFY_TOKEN_TH = os.getenv("VERIFY_TOKEN_TH", "test_token_th")
# 互換用（既存コードが参照している可能性があるので Threads と合わせる）
TH_APP_ID = THREADS_APP_ID
TH_APP_SECRET = THREADS_APP_SECRET

# Claude AI API
ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY", "")

DEFAULT_API_VERSION = os.getenv("DEFAULT_API_VERSION", "v23.0")
WORKER_INTERVAL_SEC = int(os.getenv("WORKER_INTERVAL_SEC", "5"))

LOG_DIR = BASE_DIR / "deploy"
LOG_DIR.mkdir(parents=True, exist_ok=True)  # 念のため
LOG_FILE = LOG_DIR / "app.log"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {
            "format": "%(asctime)s [%(levelname)s] %(name)s: %(message)s",
        },
    },
    "handlers": {
        "console_stream": {  # 既存の標準出力も維持
            "class": "logging.StreamHandler",
        },
        "file": {  # ← これで /app/deploy/app.log に必ず出力
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(LOG_FILE),
            "maxBytes": 2 * 1024 * 1024,
            "backupCount": 3,
            "formatter": "simple",
        },
    },
    "root": {
        "handlers": ["console_stream", "file"],
        "level": "INFO",
    },
}

META_APP_ID = os.getenv("META_APP_ID", "")
META_APP_SECRET = os.getenv("META_APP_SECRET", "")
# デフォルトは console_public の webhook URL を自動解決
META_WEBHOOK_VERIFY_TOKEN = os.getenv("META_WEBHOOK_VERIFY_TOKEN", "dev-verify-token")

# OAuth のコールバック URL を固定で使いたいときは指定、未指定なら request から絶対URL生成
META_OAUTH_REDIRECT_URI = os.getenv("META_OAUTH_REDIRECT_URI", "")

# --- added by ops: ensure legacy template filters are available ---
try:
    _opts = TEMPLATES[0].setdefault("OPTIONS", {})
    _b = _opts.setdefault("builtins", [])
    if "social.templatetags.compat" not in _b:
        _b.append("social.templatetags.compat")
except Exception:
    # do not break settings import even if TEMPLATES is unusual
    pass
# --- end ops patch ---
