# Generated by Django 5.2.4 on 2025-08-09 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="THDMThread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_thread_id",
                    models.CharField(max_length=100, verbose_name="スレッドID"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
            ],
            options={
                "verbose_name": "ThreadsDMスレッド",
                "verbose_name_plural": "ThreadsDMスレッド",
                "db_table": "meta_th_dm_threads",
            },
        ),
        migrations.CreateModel(
            name="ThreadsAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=255, verbose_name="表示名"),
                ),
                (
                    "username",
                    models.CharField(max_length=255, verbose_name="ユーザー名"),
                ),
                (
                    "external_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="外部ID"
                    ),
                ),
                (
                    "token_expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="トークン期限"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "threads_user_id",
                    models.CharField(max_length=100, verbose_name="ThreadsユーザーID"),
                ),
                (
                    "access_token",
                    models.TextField(
                        blank=True, null=True, verbose_name="アクセストークン"
                    ),
                ),
                (
                    "webhook_verify_token",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Webhook検証トークン",
                    ),
                ),
            ],
            options={
                "verbose_name": "Threadsアカウント",
                "verbose_name_plural": "Threadsアカウント",
                "db_table": "meta_th_accounts",
            },
        ),
        migrations.CreateModel(
            name="THDMMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("IN", "受信"), ("OUT", "送信")],
                        max_length=3,
                        verbose_name="方向",
                    ),
                ),
                ("text", models.TextField(verbose_name="本文")),
                ("sent_at", models.DateTimeField(verbose_name="送信時間")),
                (
                    "raw_json",
                    models.JSONField(blank=True, default=dict, verbose_name="RAW"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="th.thdmthread",
                    ),
                ),
            ],
            options={
                "verbose_name": "ThreadsDMメッセージ",
                "verbose_name_plural": "ThreadsDMメッセージ",
                "db_table": "meta_th_dm_messages",
            },
        ),
        migrations.CreateModel(
            name="THPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_post_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="外部投稿ID"
                    ),
                ),
                ("posted_at", models.DateTimeField(verbose_name="投稿時間")),
                (
                    "caption",
                    models.TextField(blank=True, null=True, verbose_name="本文"),
                ),
                (
                    "media_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="メディアタイプ"
                    ),
                ),
                (
                    "media_url",
                    models.URLField(blank=True, null=True, verbose_name="メディアURL"),
                ),
                ("like_count", models.IntegerField(default=0, verbose_name="いいね数")),
                (
                    "view_count",
                    models.IntegerField(blank=True, null=True, verbose_name="閲覧数"),
                ),
                (
                    "impressions",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="インプレッション"
                    ),
                ),
                ("raw_json", models.JSONField(default=dict, verbose_name="取得JSON")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="th.threadsaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Threads投稿",
                "verbose_name_plural": "Threads投稿",
                "db_table": "meta_th_posts",
            },
        ),
        migrations.AddField(
            model_name="thdmthread",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dm_threads",
                to="th.threadsaccount",
            ),
        ),
        migrations.CreateModel(
            name="THBroadcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="名称")),
                (
                    "segment",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="セグメント"
                    ),
                ),
                ("body", models.TextField(verbose_name="本文")),
                ("send_at", models.DateTimeField(verbose_name="送信日時")),
                (
                    "status",
                    models.CharField(
                        default="DRAFT", max_length=20, verbose_name="ステータス"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broadcasts",
                        to="th.threadsaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Threads時間指定配信",
                "verbose_name_plural": "Threads時間指定配信",
                "db_table": "meta_th_broadcasts",
            },
        ),
        migrations.CreateModel(
            name="THAutoReplyTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="名称")),
                ("body", models.TextField(verbose_name="本文")),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_reply_templates",
                        to="th.threadsaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Threads自動返信テンプレート",
                "verbose_name_plural": "Threads自動返信テンプレート",
                "db_table": "meta_th_auto_reply_templates",
            },
        ),
        migrations.CreateModel(
            name="THAutoReplyRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="名称")),
                ("keywords", models.TextField(verbose_name="キーワード")),
                (
                    "delay_minutes",
                    models.IntegerField(default=0, verbose_name="遅延分"),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="th.thautoreplytemplate",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_reply_rules",
                        to="th.threadsaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Threads自動返信ルール",
                "verbose_name_plural": "Threads自動返信ルール",
                "db_table": "meta_th_auto_reply_rules",
            },
        ),
        migrations.CreateModel(
            name="THScheduledPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="タイトル")),
                ("topic", models.CharField(max_length=255, verbose_name="トピック")),
                ("body", models.TextField(verbose_name="本文")),
                (
                    "media_url",
                    models.URLField(blank=True, null=True, verbose_name="メディアURL"),
                ),
                ("scheduled_at", models.DateTimeField(verbose_name="予約日時")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "下書き"),
                            ("APPROVED", "承認済み"),
                            ("SENT", "送信済み"),
                            ("FAILED", "失敗"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_posts",
                        to="th.threadsaccount",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
            ],
            options={
                "verbose_name": "Threads予約投稿",
                "verbose_name_plural": "Threads予約投稿",
                "db_table": "meta_th_scheduled_posts",
            },
        ),
        migrations.CreateModel(
            name="THWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(max_length=100, verbose_name="イベント種別"),
                ),
                (
                    "received_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="受信日時"),
                ),
                ("payload", models.JSONField(default=dict, verbose_name="ペイロード")),
                (
                    "processed",
                    models.BooleanField(default=False, verbose_name="処理済"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhook_events",
                        to="th.threadsaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "ThreadsWebhookイベント",
                "verbose_name_plural": "ThreadsWebhookイベント",
                "db_table": "meta_th_webhook_events",
            },
        ),
    ]
