# Generated by Django 5.2.4 on 2025-09-17 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('th', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadsaccount',
            name='permissions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='threadsaccount',
            name='webhook_subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='threadsaccount',
            name='webhook_subscribed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='threadsaccount',
            name='access_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='threadsaccount',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
