# Generated by Django 5.2.4 on 2025-09-17 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('th', '0002_threadsaccount_permissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadsaccount',
            name='access_token',
            field=models.TextField(blank=True, default='', verbose_name='アクセストークン'),
        ),
    ]
