# Generated by Django 5.2.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('th', '0003_alter_threadsaccount_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='thbuzzpost',
            name='media_type',
            field=models.CharField(
                blank=True, default='', help_text='text/image/video/carousel',
                max_length=20, verbose_name='メディア種別',
            ),
        ),
        migrations.AddField(
            model_name='thbuzzpost',
            name='media_urls',
            field=models.JSONField(
                blank=True, default=list,
                help_text='画像/動画URLの配列 [{"type":"image","url":"...","width":0,"height":0}, ...]',
                verbose_name='メディアURL一覧',
            ),
        ),
    ]
