# Generated by Django 5.2.4 on 2026-02-06 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('th', '0003_alter_threadsaccount_access_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='THBuzzAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='アカウント名')),
                ('display_name', models.CharField(blank=True, default='', max_length=255, verbose_name='表示名')),
                ('bio', models.TextField(blank=True, default='', verbose_name='自己紹介')),
                ('followers_count', models.IntegerField(blank=True, null=True, verbose_name='フォロワー数')),
                ('following_count', models.IntegerField(blank=True, null=True, verbose_name='フォロー数')),
                ('is_verified', models.BooleanField(default=False, verbose_name='認証バッジ')),
                ('profile_url', models.URLField(blank=True, default='', verbose_name='プロフィールURL')),
                ('raw_json', models.JSONField(blank=True, default=dict, verbose_name='取得時の生データ')),
                ('first_scraped_at', models.DateTimeField(auto_now_add=True, verbose_name='初回取得日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新')),
            ],
            options={
                'verbose_name': 'Threadsバズ投稿者',
                'verbose_name_plural': 'Threadsバズ投稿者',
                'db_table': 'meta_th_buzz_authors',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='THBuzzSearchJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.TextField(help_text='JSON配列形式 例: ["AI", "副業"]', verbose_name='検索キーワード')),
                ('status', models.CharField(choices=[('PENDING', '待機中'), ('RUNNING', '実行中'), ('COMPLETED', '完了'), ('FAILED', '失敗')], default='PENDING', max_length=20, verbose_name='ステータス')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='予約実行日時')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='開始日時')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完了日時')),
                ('result_count', models.IntegerField(default=0, verbose_name='取得件数')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='エラーメッセージ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': 'バズ検索ジョブ',
                'verbose_name_plural': 'バズ検索ジョブ',
                'db_table': 'meta_th_buzz_search_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='THBuzzPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_url', models.URLField(blank=True, default='', verbose_name='投稿URL')),
                ('text_content', models.TextField(blank=True, default='', verbose_name='投稿文面')),
                ('like_count', models.IntegerField(default=0, verbose_name='いいね数')),
                ('reply_count', models.IntegerField(default=0, verbose_name='リプライ数')),
                ('repost_count', models.IntegerField(default=0, verbose_name='リポスト数')),
                ('impressions', models.IntegerField(blank=True, null=True, verbose_name='インプレッション数')),
                ('engagement_rate', models.FloatField(blank=True, null=True, verbose_name='エンゲージメント率(%)')),
                ('engagement_score', models.FloatField(blank=True, null=True, verbose_name='バズスコア')),
                ('is_viral', models.BooleanField(default=False, verbose_name='バズ判定')),
                ('search_keyword', models.CharField(blank=True, default='', max_length=255, verbose_name='検索キーワード')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='投稿日時')),
                ('scraped_at', models.DateTimeField(auto_now_add=True, verbose_name='取得日時')),
                ('raw_json', models.JSONField(blank=True, default=dict, verbose_name='取得時の生データ')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buzz_posts', to='th.thbuzzauthor', verbose_name='投稿者')),
            ],
            options={
                'verbose_name': 'Threadsバズ投稿',
                'verbose_name_plural': 'Threadsバズ投稿',
                'db_table': 'meta_th_buzz_posts',
                'ordering': ['-scraped_at'],
            },
        ),
    ]
