# Generated by Django 5.2.4 on 2026-02-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('th', '0004_thbuzzauthor_thbuzzsearchjob_thbuzzpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='thbuzzauthor',
            name='account_age_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='推定アカウント日数'),
        ),
        migrations.AddField(
            model_name='thbuzzauthor',
            name='avg_likes',
            field=models.FloatField(blank=True, null=True, verbose_name='平均いいね数'),
        ),
        migrations.AddField(
            model_name='thbuzzauthor',
            name='avg_replies',
            field=models.FloatField(blank=True, null=True, verbose_name='平均リプライ数'),
        ),
        migrations.AddField(
            model_name='thbuzzauthor',
            name='category_tags',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='カテゴリタグ'),
        ),
        migrations.AddField(
            model_name='thbuzzauthor',
            name='earliest_post_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最古の投稿日時'),
        ),
        migrations.AddField(
            model_name='thbuzzauthor',
            name='followers_per_day',
            field=models.FloatField(blank=True, null=True, verbose_name='1日あたりフォロワー増'),
        ),
        migrations.AddField(
            model_name='thbuzzauthor',
            name='growth_score',
            field=models.FloatField(blank=True, null=True, verbose_name='急成長スコア'),
        ),
        migrations.AddField(
            model_name='thbuzzauthor',
            name='latest_post_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最新の投稿日時'),
        ),
        migrations.AddField(
            model_name='thbuzzauthor',
            name='memo',
            field=models.TextField(blank=True, default='', verbose_name='メモ'),
        ),
        migrations.AddField(
            model_name='thbuzzauthor',
            name='total_post_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='総投稿数'),
        ),
    ]
