# Generated by Django 5.2.4 on 2026-02-11 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('th', '0004_thbuzzpost_media_type_thbuzzpost_media_urls'),
        ('th', '0005_thbuzzauthor_account_age_days_thbuzzauthor_avg_likes_and_more'),
    ]

    operations = [
    ]
