# Generated by Django 5.2.4 on 2026-02-11 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('th', '0005_thbuzzauthor_is_favorited'),
        ('th', '0006_merge_20260211_1008'),
    ]

    operations = [
    ]
