# Generated by Django 5.2.4 on 2026-02-13 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('th', '0006_thbuzzsearchjob_job_type'),
        ('th', '0007_merge_20260211_2352'),
    ]

    operations = [
    ]
