# Generated by Django 5.2.4 on 2026-02-13 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('th', '0007_thbuzzauthor_is_concept_candidate'),
        ('th', '0009_thbuzzauthor_quality_fields'),
    ]

    operations = [
    ]
