# Generated by Django 5.2.4 on 2026-02-13 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('th', '0010_merge_20260213_2006'),
        ('th', '0010_thbuzzauthor_is_excluded'),
    ]

    operations = [
    ]
