# Generated by Django 5.2.4 on 2026-02-13 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('th', '0011_add_buzz_indexes'),
        ('th', '0011_merge_20260214_0039'),
    ]

    operations = [
    ]
