# Generated by Django 5.2.4 on 2026-02-14 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('th', '0012_merge_0011_add_buzz_indexes_0011_merge_20260214_0039'),
        ('th', '0012_thbuzzsearchjob_error_traceback'),
    ]

    operations = [
    ]
