# Generated by Django 5.2.4 on 2026-02-14 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('th', '0013_merge_20260214_1022'),
        ('th', '0013_thbuzzauthor_profile_pic_url'),
    ]

    operations = [
    ]
