# Generated by Django 5.2.4 on 2026-02-14 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('th', '0014_add_fortune_classification_fields'),
        ('th', '0014_merge_20260214_1058'),
    ]

    operations = [
    ]
