# Generated by Codex on 2026-03-01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_appraisalcharacter_concept_fields'),
        ('th', '0017_alter_thpost_media_url_alter_thscheduledpost_media_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='プロジェクト名')),
                ('status', models.CharField(choices=[('DRAFT', '下書き'), ('ANALYZING', '分析中'), ('CONCEPTS_GENERATED', 'コンセプト案生成済み'), ('DETAILING', '詳細化中'), ('COMPLETED', '完了')], default='DRAFT', max_length=30, verbose_name='ステータス')),
                ('analysis_result', models.JSONField(blank=True, default=dict, verbose_name='AI分析結果（統合）')),
                ('analysis_summary', models.TextField(blank=True, default='', verbose_name='分析まとめ')),
                ('concept_proposals', models.JSONField(blank=True, default=list, verbose_name='ずらしコンセプト案')),
                ('selected_proposal_index', models.IntegerField(blank=True, null=True, verbose_name='選択した案番号')),
                ('detailed_concept_md', models.TextField(blank=True, default='', verbose_name='詳細化結果（MD形式）')),
                ('user_feedback', models.TextField(blank=True, default='', verbose_name='ユーザー要望メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concept_projects', to='social.appraisalcharacter', verbose_name='生成キャラクター')),
            ],
            options={
                'verbose_name': 'コンセプト設計プロジェクト',
                'verbose_name_plural': 'コンセプト設計プロジェクト',
                'db_table': 'meta_th_concept_projects',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ConceptProjectAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_analysis', models.JSONField(blank=True, default=dict, verbose_name='AI分析結果')),
                ('ai_summary', models.TextField(blank=True, default='', verbose_name='特徴まとめ')),
                ('order', models.IntegerField(default=0, verbose_name='表示順')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_usages', to='th.thbuzzauthor', verbose_name='参考アカウント')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_authors', to='th.conceptproject', verbose_name='プロジェクト')),
            ],
            options={
                'verbose_name': 'コンセプト参考アカウント',
                'verbose_name_plural': 'コンセプト参考アカウント',
                'db_table': 'meta_th_concept_project_authors',
                'ordering': ['order'],
                'unique_together': {('project', 'author')},
            },
        ),
    ]
