# Generated by Django 5.2.5 on 2026-03-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("th", "0018_conceptproject_and_authors"),
    ]

    operations = [
        migrations.AddField(
            model_name="thbuzzauthor",
            name="deep_scan_fail_count",
            field=models.IntegerField(default=0, verbose_name="深堀スキャン連続失敗回数"),
        ),
        migrations.AddField(
            model_name="thbuzzauthor",
            name="deep_scan_last_attempt_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="深堀スキャン最終試行日時"),
        ),
        migrations.AddField(
            model_name="thbuzzauthor",
            name="deep_scan_last_error",
            field=models.TextField(blank=True, default="", verbose_name="深堀スキャン最終エラー"),
        ),
        migrations.AddIndex(
            model_name="thbuzzauthor",
            index=models.Index(fields=["deep_scan_fail_count"], name="bza_deep_scan_fail_count"),
        ),
    ]
