# Generated by Django 5.2.4 on 2026-03-09 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('th', '0019_thbuzzauthor_deep_scan_failure_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='thscheduledpost',
            name='concept_project',
            field=models.ForeignKey(blank=True, help_text='生成元のコンセプトプロジェクト', null=True, on_delete=django.db.models.deletion.SET_NULL, to='th.conceptproject', verbose_name='コンセプトプロジェクト'),
        ),
        migrations.AddField(
            model_name='thscheduledpost',
            name='engagement',
            field=models.IntegerField(default=0, verbose_name='エンゲージメント数'),
        ),
        migrations.AddField(
            model_name='thscheduledpost',
            name='external_post_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='外部投稿ID'),
        ),
        migrations.AddField(
            model_name='thscheduledpost',
            name='impressions',
            field=models.IntegerField(default=0, verbose_name='インプレッション数'),
        ),
        migrations.AddField(
            model_name='thscheduledpost',
            name='insights_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='インサイト更新日時'),
        ),
        migrations.AddField(
            model_name='thscheduledpost',
            name='source_buzz_post',
            field=models.ForeignKey(blank=True, help_text='リライト元のバズ投稿', null=True, on_delete=django.db.models.deletion.SET_NULL, to='th.thbuzzpost', verbose_name='リライト元バズ投稿'),
        ),
    ]
