# Generated by Django 5.2.4 on 2026-05-22 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('th', '0020_thscheduledpost_concept_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例: arayasaki7、research_01', max_length=64, unique=True, verbose_name='識別名')),
                ('threads_username', models.CharField(blank=True, default='', max_length=128, verbose_name='Threadsユーザー名')),
                ('storage_state_path', models.CharField(help_text='例: /app/deploy/threads_session_arayasaki7.json', max_length=256, verbose_name='セッションファイルパス')),
                ('status', models.CharField(choices=[('NEW', '新規追加（未起動）'), ('VPS_WARMUP', 'VPSウォームアップ中（超低頻度）'), ('ACTIVE', '通常稼働'), ('SUSPENDED', '凍結検知／停止中')], default='NEW', max_length=20, verbose_name='運用ステータス')),
                ('warmup_started_at', models.DateTimeField(blank=True, help_text='VPS_WARMUP 状態に遷移した日時', null=True, verbose_name='VPSウォームアップ開始日時')),
                ('warmup_duration_days', models.IntegerField(default=14, help_text='期間経過後に ACTIVE へ自動昇格（auto_promote=True の場合）', verbose_name='ウォームアップ期間(日)')),
                ('auto_promote', models.BooleanField(default=True, verbose_name='期間経過で自動昇格')),
                ('suspended_at', models.DateTimeField(blank=True, null=True, verbose_name='停止日時')),
                ('suspended_reason', models.TextField(blank=True, default='', verbose_name='停止理由')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最終使用日時')),
                ('daily_request_count', models.IntegerField(default=0, verbose_name='日次リクエスト数')),
                ('daily_count_reset_at', models.DateField(blank=True, null=True, verbose_name='日次カウンタ最終リセット日')),
                ('memo', models.TextField(blank=True, default='', verbose_name='運用メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'リサーチ用アカウント',
                'verbose_name_plural': 'リサーチ用アカウント',
                'db_table': 'meta_th_research_accounts',
            },
        ),
        migrations.CreateModel(
            name='ScraperNotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='メール通知有効')),
                ('recipient_emails', models.TextField(blank=True, default='', help_text='例: alert@example.com, ops@example.com', verbose_name='通知先メール（カンマ区切り）')),
                ('notify_events', models.JSONField(blank=True, default=list, help_text='ScraperEventLog の event_type 文字列の配列', verbose_name='通知イベント種別')),
                ('min_level', models.CharField(choices=[('DEBUG', 'DEBUG'), ('INFO', 'INFO'), ('WARN', 'WARN'), ('ERROR', 'ERROR'), ('CRITICAL', 'CRITICAL')], default='WARN', max_length=10, verbose_name='通知レベル下限')),
                ('aggregate_window_min', models.IntegerField(default=30, help_text='同種イベントを N 分以内に閾値件数以上で 1 通にまとめる', verbose_name='集約ウィンドウ(分)')),
                ('aggregate_threshold', models.IntegerField(default=3, verbose_name='集約しきい値(件)')),
                ('auto_stop_on_suspension', models.BooleanField(default=True, verbose_name='SUSPENSION_DETECTED 時に自動停止')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'スクレイパ通知設定',
                'verbose_name_plural': 'スクレイパ通知設定',
                'db_table': 'meta_th_scraper_notification_config',
            },
        ),
        migrations.CreateModel(
            name='ScraperEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('LOGIN_SUCCESS', 'ログイン成功'), ('LOGIN_FAILED', 'ログイン失敗'), ('RATE_LIMIT_HIT', 'レート制限到達'), ('HTTP_403', 'HTTP 403'), ('HTTP_429', 'HTTP 429'), ('SUSPENSION_DETECTED', '凍結検知'), ('JOB_START', 'ジョブ開始'), ('JOB_COMPLETE', 'ジョブ完了'), ('JOB_FAILED', 'ジョブ失敗'), ('DAILY_LIMIT_REACHED', '日次上限到達'), ('QUIET_HOURS_ENTER', '深夜停止突入'), ('PROXY_ERROR', 'プロキシエラー'), ('WARMUP_PROMOTED', 'ウォームアップ→稼働昇格')], max_length=32, verbose_name='イベント種別')),
                ('level', models.CharField(choices=[('DEBUG', 'DEBUG'), ('INFO', 'INFO'), ('WARN', 'WARN'), ('ERROR', 'ERROR'), ('CRITICAL', 'CRITICAL')], default='INFO', max_length=10, verbose_name='レベル')),
                ('message', models.TextField(blank=True, default='', verbose_name='メッセージ')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='付加データ')),
                ('notified', models.BooleanField(default=False, verbose_name='通知送信済み')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='発生日時')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='th.researchaccount', verbose_name='対象アカウント')),
            ],
            options={
                'verbose_name': 'スクレイパイベント',
                'verbose_name_plural': 'スクレイパイベント',
                'db_table': 'meta_th_scraper_event_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='sel_created_desc'), models.Index(fields=['event_type'], name='sel_event_type'), models.Index(fields=['level'], name='sel_level')],
            },
        ),
    ]
