# Generated by Django 5.2.4 on 2026-06-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('th', '0021_researchaccount_scrapernotificationconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchaccount',
            name='current_operation_mode',
            field=models.CharField(choices=[('IDLE', 'IDLE（誰も操作していない）'), ('VPS', 'VPS（research-browser で閲覧中）'), ('MOBILE', 'MOBILE（スマホ実機で操作中）')], default='IDLE', max_length=10, verbose_name='現在の操作モード'),
        ),
        migrations.AddField(
            model_name='researchaccount',
            name='operation_mode_locked_until',
            field=models.DateTimeField(blank=True, help_text='この時刻まで別モードに切り替えられない（15分 cooldown）', null=True, verbose_name='モード切替ロック期限'),
        ),
        migrations.AddField(
            model_name='researchaccount',
            name='operation_mode_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='モード開始日時'),
        ),
        migrations.AlterField(
            model_name='researchaccount',
            name='name',
            field=models.CharField(help_text='例: arayahide3、research_01', max_length=64, unique=True, verbose_name='識別名'),
        ),
        migrations.AlterField(
            model_name='researchaccount',
            name='storage_state_path',
            field=models.CharField(help_text='例: /app/deploy/threads_session_arayahide3.json', max_length=256, verbose_name='セッションファイルパス'),
        ),
    ]
