# Generated by Django 5.2.4 on 2025-08-09 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DMReplyTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="名称")),
                ("reply_text", models.TextField(verbose_name="返信本文")),
            ],
        ),
        migrations.CreateModel(
            name="FacebookAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="名前")),
                (
                    "facebook_user_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="FacebookユーザーID"
                    ),
                ),
                (
                    "app_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="アプリID"
                    ),
                ),
                (
                    "app_secret",
                    models.TextField(
                        blank=True, null=True, verbose_name="アプリシークレット"
                    ),
                ),
                (
                    "access_token",
                    models.TextField(
                        blank=True, null=True, verbose_name="アクセストークン"
                    ),
                ),
                (
                    "access_token_expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="アクセストークン有効期限"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ThreadsApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="名前")),
                (
                    "threads_app_id",
                    models.CharField(max_length=100, verbose_name="ThreadsアプリID"),
                ),
                (
                    "threads_app_secret",
                    models.TextField(verbose_name="Threadsアプリシークレット"),
                ),
                ("callback_url", models.URLField(verbose_name="コールバックURL")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("THREADS", "Threads"), ("INSTAGRAM", "Instagram")],
                        max_length=20,
                        verbose_name="プラットフォーム",
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="受信時間"),
                ),
                (
                    "event_type",
                    models.CharField(max_length=100, verbose_name="イベント種類"),
                ),
                ("payload", models.JSONField(default=dict, verbose_name="ペイロード")),
                (
                    "processed",
                    models.BooleanField(default=False, verbose_name="処理済み"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DMMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("THREADS", "Threads"), ("INSTAGRAM", "Instagram")],
                        max_length=20,
                        verbose_name="プラットフォーム",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(null=True)),
                (
                    "sender_external_user_id",
                    models.CharField(max_length=100, verbose_name="送信者ID"),
                ),
                ("text", models.TextField(verbose_name="本文")),
                ("received_at", models.DateTimeField(verbose_name="受信時間")),
                ("raw_json", models.JSONField(default=dict, verbose_name="受信JSON")),
                (
                    "content_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AutoReplyRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="名称")),
                (
                    "platform",
                    models.CharField(
                        choices=[("THREADS", "Threads"), ("INSTAGRAM", "Instagram")],
                        max_length=20,
                        verbose_name="プラットフォーム",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(null=True)),
                ("keywords", models.TextField(verbose_name="キーワード")),
                (
                    "delay_minutes",
                    models.IntegerField(default=0, verbose_name="遅延分"),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "content_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "reply_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="social.dmreplytemplate",
                        verbose_name="返信テンプレート",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InstagramAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=255, verbose_name="表示名"),
                ),
                (
                    "instagram_user_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="InstagramユーザーID"
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=255, verbose_name="ユーザー名"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "linked_facebook",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="social.facebookaccount",
                        verbose_name="紐付けFacebook",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("THREADS", "Threads"), ("INSTAGRAM", "Instagram")],
                        max_length=20,
                        verbose_name="プラットフォーム",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "external_post_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="外部投稿ID"
                    ),
                ),
                ("posted_at", models.DateTimeField(verbose_name="投稿時間")),
                ("content", models.TextField(verbose_name="内容")),
                ("like_count", models.IntegerField(default=0, verbose_name="いいね数")),
                (
                    "view_count",
                    models.IntegerField(blank=True, null=True, verbose_name="閲覧数"),
                ),
                ("raw_json", models.JSONField(default=dict, verbose_name="取得JSON")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScheduledPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("THREADS", "Threads"), ("INSTAGRAM", "Instagram")],
                        max_length=20,
                        verbose_name="プラットフォーム",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=255, verbose_name="タイトル")),
                ("topic", models.CharField(max_length=255, verbose_name="トピック")),
                ("body", models.TextField(verbose_name="本文")),
                ("scheduled_at", models.DateTimeField(verbose_name="投稿予定時刻")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "下書き"),
                            ("APPROVED", "承認済み"),
                            ("SENT", "送信済み"),
                            ("FAILED", "失敗"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ThreadsAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=255, verbose_name="表示名"),
                ),
                (
                    "threads_user_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="ThreadsユーザーID"
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=255, verbose_name="ユーザー名"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "linked_facebook",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="social.facebookaccount",
                        verbose_name="紐付けFacebook",
                    ),
                ),
                (
                    "default_app",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="social.threadsapp",
                        verbose_name="デフォルトアプリ",
                    ),
                ),
            ],
        ),
    ]
