# Generated by Django 5.2.4 on 2025-09-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_job_and_dm_updates'),
    ]

    operations = [
        migrations.CreateModel(
            name='DMContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ig_user_id', models.CharField(db_index=True, max_length=64)),
                ('psid', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('thread_key', models.CharField(blank=True, max_length=128, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('last_event_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('ig_user_id', 'psid')},
            },
        ),
    ]
