# Generated by Django 5.2.4 on 2026-02-26 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ig', '0009_rename_meta_ig_pos_post_id_idx_meta_ig_pos_post_id_342b0f_idx'),
        ('social', '0003_dmcontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppraisalCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='キャラクター名')),
                ('concept', models.TextField(blank=True, verbose_name='世界観・設定')),
                ('writing_style', models.TextField(blank=True, verbose_name='口調・文体')),
                ('target_audience', models.TextField(blank=True, verbose_name='ターゲット層')),
                ('divination_methods', models.JSONField(blank=True, default=list, verbose_name='使用占術リスト')),
                ('background_story', models.TextField(blank=True, verbose_name='経歴設定')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('ig_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisal_characters', to='ig.instagrambusinessaccount', verbose_name='IGアカウント')),
                ('th_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisal_characters', to='social.threadsaccount', verbose_name='THアカウント')),
            ],
            options={
                'verbose_name': '鑑定キャラクター',
                'verbose_name_plural': '鑑定キャラクター',
            },
        ),
        migrations.CreateModel(
            name='AppraisalCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('THREADS', 'Threads'), ('INSTAGRAM', 'Instagram')], max_length=20, verbose_name='プラットフォーム')),
                ('platform_user_id', models.CharField(max_length=100, verbose_name='プラットフォームユーザーID')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='ユーザー名')),
                ('display_name', models.CharField(blank=True, max_length=255, verbose_name='表示名')),
                ('birthdate', models.CharField(blank=True, max_length=20, verbose_name='生年月日')),
                ('profile_summary', models.TextField(blank=True, verbose_name='プロフィール要約')),
                ('personality_analysis', models.TextField(blank=True, verbose_name='AI性格分析')),
                ('posts_fetched_at', models.DateTimeField(blank=True, null=True, verbose_name='投稿取得日時')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
            ],
            options={
                'verbose_name': '鑑定顧客',
                'verbose_name_plural': '鑑定顧客',
                'unique_together': {('platform', 'platform_user_id')},
            },
        ),
        migrations.CreateModel(
            name='AppraisalCustomerPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_url', models.URLField(blank=True, max_length=500, verbose_name='投稿URL')),
                ('text_content', models.TextField(blank=True, verbose_name='投稿内容')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='投稿日時')),
                ('like_count', models.IntegerField(default=0, verbose_name='いいね数')),
                ('reply_count', models.IntegerField(default=0, verbose_name='リプライ数')),
                ('raw_json', models.JSONField(blank=True, default=dict, verbose_name='生データ')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='social.appraisalcustomer', verbose_name='顧客')),
            ],
            options={
                'verbose_name': '顧客投稿キャッシュ',
                'verbose_name_plural': '顧客投稿キャッシュ',
                'ordering': ['-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='AppraisalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='テンプレート名')),
                ('category', models.CharField(choices=[('FREE', '無料鑑定'), ('PAID_LOW', '有料（低額）'), ('PAID_MID', '有料（中額）'), ('PAID_HIGH', '有料（高額）'), ('FOLLOWUP', 'フォローアップ')], default='FREE', max_length=20, verbose_name='カテゴリ')),
                ('system_prompt', models.TextField(blank=True, verbose_name='システムプロンプト（MD形式）')),
                ('user_prompt_template', models.TextField(blank=True, verbose_name='ユーザープロンプトテンプレート')),
                ('word_count_min', models.IntegerField(default=600, verbose_name='最小文字数')),
                ('word_count_max', models.IntegerField(default=1000, verbose_name='最大文字数')),
                ('sort_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='social.appraisalcharacter', verbose_name='キャラクター')),
            ],
            options={
                'verbose_name': '鑑定テンプレート',
                'verbose_name_plural': '鑑定テンプレート',
                'ordering': ['character', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AppraisalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.CharField(blank=True, max_length=20, verbose_name='生年月日')),
                ('concern', models.TextField(blank=True, verbose_name='相談内容')),
                ('divination', models.CharField(blank=True, max_length=50, verbose_name='占術')),
                ('generated_text', models.TextField(blank=True, verbose_name='生成テキスト')),
                ('sent_text', models.TextField(blank=True, verbose_name='送信テキスト')),
                ('system_prompt_used', models.TextField(blank=True, verbose_name='使用システムプロンプト')),
                ('user_prompt_used', models.TextField(blank=True, verbose_name='使用ユーザープロンプト')),
                ('dm_sent', models.BooleanField(default=False, verbose_name='DM送信済み')),
                ('dm_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='DM送信日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='histories', to='social.appraisalcharacter', verbose_name='キャラクター')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='histories', to='social.appraisalcustomer', verbose_name='顧客')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='histories', to='social.appraisaltemplate', verbose_name='テンプレート')),
            ],
            options={
                'verbose_name': '鑑定履歴',
                'verbose_name_plural': '鑑定履歴',
                'ordering': ['-created_at'],
            },
        ),
    ]
