# Generated by Codex on 2026-03-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_appraisalcharacter_appraisalcustomer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisalcharacter',
            name='concept_document_md',
            field=models.TextField(blank=True, default='', verbose_name='コンセプト設計書（MD形式）'),
        ),
        migrations.AddField(
            model_name='appraisalcharacter',
            name='pinned_post_samples',
            field=models.JSONField(blank=True, default=list, verbose_name='固定投稿サンプル'),
        ),
        migrations.AddField(
            model_name='appraisalcharacter',
            name='profile_bio',
            field=models.TextField(blank=True, default='', verbose_name='プロフィールbio'),
        ),
    ]
