# Generated by Django 5.2.4 on 2025-09-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('common', '共通'), ('ig', 'Instagram'), ('th', 'Threads')], default='common', max_length=16)),
                ('name', models.CharField(max_length=100)),
                ('key', models.SlugField(help_text='英数字とハイフン。ルール等から参照できます。', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('content', models.TextField(help_text='本文。{{ user_name }} のような差し込みが使えます。')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '返信テンプレート',
                'verbose_name_plural': '返信テンプレート',
                'db_table': 'console_message_templates',
                'ordering': ['-updated_at'],
            },
        ),
    ]
