# Generated by Django 5.2.4 on 2025-08-03 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DMReplyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('reply_text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('lag_seconds', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InstagramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('user_id', models.CharField(max_length=100, unique=True)),
                ('access_token', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstagramDM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dm_id', models.CharField(max_length=100, unique=True)),
                ('sender_id', models.CharField(max_length=100)),
                ('recipient_id', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sns_core.instagramaccount')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('media_url', models.URLField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField()),
                ('posted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sns_core.instagramaccount')),
            ],
        ),
        migrations.CreateModel(
            name='ThreadsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threads_user_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instagram_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sns_core.instagramaccount')),
            ],
        ),
        migrations.CreateModel(
            name='ThreadsFollowerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_count', models.IntegerField()),
                ('date', models.DateField()),
                ('threads_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sns_core.threadsaccount')),
            ],
        ),
        migrations.CreateModel(
            name='ThreadsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=100, unique=True)),
                ('text', models.TextField()),
                ('media_url', models.URLField(blank=True, null=True)),
                ('like_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('posted_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('threads_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sns_core.threadsaccount')),
            ],
        ),
    ]
